BasicFantasyBeyond/Controllers/CharacterController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BasicFantasyBeyond.Models;
using BasicFantasyBeyond.Models.CharacterModels;
using BasicFantasyBeyond.Services;
using Microsoft.AspNet.Identity;

namespace BasicFantasyBeyond.Controllers
{
    public class CharacterController : Controller
    {
        public ActionResult Index()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var service = new CharacterServices(userID);
            var model = service.GetCharacters();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(CharacterCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = CharacterServices();

            if (service.CreateCharacter(model))
            {
                var id = Guid.Parse(User.Identity.GetUserId());
                int characterID = service.GetLastCharacterIDFromUser(id);

                TempData["SaveResult"] = "Your Character was created.";
                return RedirectToAction("Details","CharacterSheet", new { id = characterID});
            }

            ModelState.AddModelError("", "Your Character could not be created.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = CharacterServices();
            var model = svc.GetCharacterByID(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = CharacterServices();
            var detail = service.GetCharacterByID(id);
            var model =
                new CharacterDetails
                {
                    OwnerID = detail.OwnerID,
                    CharacterID = detail.CharacterID,
                    CharacterName = detail.CharacterName,
                    CharacterStr = detail.CharacterStr,
                    CharacterDex = detail.CharacterDex,
                    CharacterCon = detail.CharacterCon,
                    CharacterInt = detail.CharacterInt,
                    CharacterWis = detail.CharacterWis,
                    CharacterCha = detail.CharacterCha,
                    CharacterRace = detail.CharacterRace,
                    CharacterClass = detail.CharacterClass,
                    CharacterAbilities = detail.CharacterAbilities,
                    CharacterXP = detail.CharacterXP,
                    CharacterLevel = detail.CharacterLevel,
                    CharacterAC = detail.CharacterAC,
                    CharacterHP = detail.CharacterHP,
                    HitPointRange = detail.HitPointRange,
                    CharacterAttackBonus = detail.CharacterAttackBonus,
                    CharacterNotes = detail.CharacterNotes
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, CharacterDetails model)
        {
            var service = CharacterServices();

            // Avoids "potentially dangerous characters" error when passing through model.HitPointRange"
            var hitPointRange = service.GetCharacterByID(id).HitPointRange;
            model.HitPointRange = hitPointRange;

            if (!ModelState.IsValid) return View(model);

            if (model.CharacterID != id)
            {
                ModelState.AddModelError("", "Id Missmatch");
                return View(model);
            }

            if (model.CharacterHP < model.HitPointRange.Min() || model.CharacterHP > model.HitPointRange.Max())
            {
                ModelState.AddModelError("", "Your HP was too high or too low");
                return View(model);
            }

            if (service.UpdateCharacter(model))
            {
                int characterID = id;

                TempData["SaveResult"] = "Your character was updated.";
                return RedirectToAction("Details","CharacterSheet",new { id = characterID });
            }

            ModelState.AddModelError("", "Your character could not be updated.");
            return View(model);
        }


        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = CharacterServices();
            var model = svc.GetCharacterByID(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteCharacter(int id)
        {
            var service = CharacterServices();

            service.DeleteCharacter(id);

            TempData["SaveResult"] = "Your character was deleted";

            return RedirectToAction("Index");
        }

        private CharacterServices CharacterServices()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var service = new CharacterServices(userID);
            return service;
        }
    }
}

BasicFantasyBeyond/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BasicFantasyBeyond.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

BasicFantasyBeyond/Controllers/ItemsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using BasicFantasyBeyond.Models;
using BasicFantasyBeyond.Models.EquipmentModels;
using BasicFantasyBeyond.Services;
using Microsoft.AspNet.Identity;

namespace BasicFantasyBeyond.Controllers
{
    public class ItemsController : Controller
    {
        public ActionResult Index()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var service = new ItemServices(userID);
            var model = service.GetItems();

            return View(model);
        }

        public ActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create(ItemCreate model)
        {
            if (!ModelState.IsValid)
            {
                return View(model);
            }

            var service = ItemServices();

            if (service.CreateEquipment(model))
            {
                TempData["SaveResult"] = "The equipment was created.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The equipment could not be created.");
            return View(model);
        }

        public ActionResult Details(int id)
        {
            var svc = ItemServices();
            var model = svc.GetItemByID(id);

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var service = ItemServices();
            var detail = service.GetItemByID(id);
            var model =
                new ItemDetails
                {
                    ItemID = detail.ItemID,
                    ItemName=detail.ItemName,
                    ItemType = detail.ItemType,
                    IsEquipped = detail.IsEquipped,
                    Damage = detail.Damage,
                    DamageType = detail.DamageType,
                    ArmorClassBonus = detail.ArmorClassBonus,
                    ArmorType = detail.ArmorType,
                    ItemNotes = detail.ItemNotes
                };
            return View(model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(int id, ItemDetails model)
        {
            if (!ModelState.IsValid) return View(model);

            if(model.ItemID != id)
            {
                ModelState.AddModelError("", "Id Missmatch");
                return View(model);
            }

            var service = ItemServices();

            if (service.UpdateItem(model))
            {
                TempData["SaveResult"] = "The equipment was updated.";
                return RedirectToAction("Index");
            }

            ModelState.AddModelError("", "The equipment could not be updated.");
            return View(model);
        }


        [ActionName("Delete")]
        public ActionResult Delete(int id)
        {
            var svc = ItemServices();
            var model = svc.GetItemByID(id);

            return View(model);
        }

        [HttpPost]
        [ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteEquipment(int id)
        {
            var service = ItemServices();
            
            service.DeleteItem(id);

            TempData["SaveResult"] = "The equipment was deleted";

            return RedirectToAction("Index");
        }

        private ItemServices ItemServices()
        {
            var userID = Guid.Parse(User.Identity.GetUserId());
            var service = new ItemServices(userID);
            return service;
        }    }
}

BasicFantasyBeyond/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

BasicFantasyBeyond/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

BasicFantasyBeyond/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="backgroundImg img-fluid">
    <div class="jumbotron border border-top-0 border-dark rounded-0 bg-transparent pt-4 pb-3">
        <h1>Basic Fantasy Beyond</h1>
        <hr />
        <p class="lead">Basic Fantasy Beyond is an online character sheet application for use with the tabletop RPG "Basic Fantasy".  All of the rules and supplements are available to download for free from <a href="http://www.basicfantasy.org" class="text-decoration-none text-dark">BasicFantasy.org</a> with no strings attached.</p>
        <p><a href="https://www.basicfantasy.org" target="blank" class="btn btn-dark btn-lg rounded-0 mt-2 mb-0">Learn more or download rules &raquo;</a></p>
    </div>

    <div class="row px-md-3">
        <div class="col-md-4 bg-transparent border border-dark rounded-0 pt-2">
            <h3>Create a character</h3>
            <hr />
            <p>
                Basic Fantasy Beyond lets you create a character from scratch in less than ten minutes.  All you need is a set of dice and you're ready to go!
            </p>
            <p>
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-dark rounded-0" href='@Url.Action("Create", "Character")'>Create a Character &raquo;</a>
                    }
                    else
                    {
                        @Html.ActionLink("Log in to create a Character", "Login", "Account", routeValues: null, htmlAttributes: new { id = "loginLink", @class = "btn btn-dark rounded-0 " })
                    }
                }
            </p>
        </div>
        <div class="col-md-4 bg-transparent border border-dark rounded-0 pt-2">
            <h3>View My Characters</h3>
            <hr />
            <p>View a list of your created characters.</p>
            <p>
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-dark rounded-0" href='@Url.Action("Index","Character")'>View Characters &raquo;</a>
                    }
                    else
                    {
                        @Html.ActionLink("Log in to view your Characters", "Login", "Account", "", new { id = "loginLink", @class = "btn btn-dark rounded-0" })
                    }
                }
            </p>
        </div>
        <div class="col-md-4 bg-transparent border border-dark rounded-0 pt-2">
            <h3>View list of Items</h3>
            <hr />
            <p>Basic Fantasy Beyond comes with all of the Core items already created, but your Game Master can create his or her own custom items for anyone to use.</p>
            <p>
                @{
                    if (User.Identity.IsAuthenticated)
                    {
                        <a class="btn btn-dark rounded-0" href='@Url.Action("Index","Items")'>View Items &raquo;</a>
                    }
                    else
                    {
                        @Html.ActionLink("Log in to view Items", "Login", "Account", "", new { id = "loginLink", @class = "btn btn-dark rounded-0" })
                    }
                }
            </p>
        </div>
    </div>
</div>